function load_bash_module {
    if [ -f $1/$2.bash ]; then
        source $1/$2.bash
    else
        echo "Bash module $2 not found in $1."
    fi
}

bash_d=~/.bash.d
bash_modules="common mac git python java"

if [ ! -d ${bash_d} ]; then
    echo "Module directory not found: ${bash_d}"
    exit 1
fi

for module in $bash_modules
do
    load_bash_module $bash_d $module
done
